# Site settings
title: GNaP Docs
email: dotnet@infrabel.be
description: "The official GNaP documentation"
baseurl: ""
url: "http://infrabel.github.io/docs-gnap"

# Build settings
markdown: kramdown
permalink: pretty
