# Site settings
title: GNaP Docs
email: dotnet@infrabel.be
description: "The official GNaP documentation"
baseurl: "/"
themeurl: "/node_modules/gnap-theme-gnap/"
url: "http://gnap.io"

# Build settings
markdown: kramdown
permalink: pretty
#highlighter: rouge

kramdown:
  input: GFM
